# Site settings
title: Safwan Abdel Aal
email: safwanabdelaal@gmail.com
description: >-
  learning by doing
lang: en-US
timezone: Asia/Amman
mode: light

# Profile settings
author:
  name: Safwan Abdel Aal
  bio: >-
    Hi there. I am Safwan. This is my little space on the internet where I sometimes share some bits from time to time.
    <br>
    <a href="https://github.com/sabdelaal" rel="noreferrer" target="_blank">@github</a>
    <a href="https://www.linkedin.com/in/safwanabdelaal/" rel="noreferrer" target="_blank">@linkedin</a>
  username: Safwan Abdel Aal
  avatar: /assets/img/avatar.jpg

# Social media
github_username: sabdelaal
linkedin_username: safwanabdelaal
instagram_username: safwanjo

# URL settings
url: "https://sabdelaal.github.io"  # Update this if using GitHub Pages URL
baseurl: ""  # Leave this blank for GitHub Pages
permalink: /:categories/:title

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Build settings
theme: minima
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules

# Analytics and tracking (optional)
google_analytics: ""
fb_appid: ""
