# Site settings
title: Safwan Abdel Aal # site title
email: safwanabdelaal@gmail.com
description: >- # site description
  learning by doing
lang: en-US # default lang
timezone: Asia/Amman # set your timezone
#image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
mode: light # default theme "dark" | "light"
# used for utterance
# repo: breuerfelix/breuerfelix.github.io CHANGE THIS


# Profile settings
author:
  name: Safwan Abdel Aal # author name
  bio: >- # tell to the world
    Hi there. I am Safwan. This is my little space on the internet where I sometimes share some bits from time to time.
    <br>
    <a href="https://github.com/sabdelaal" rel="noreferrer" target="_blank">@github</a>
    <a href="https://www.linkedin.com/in/safwanabdelaal/" rel="noreferrer" target="_blank">@linkedin</a>

  username: Safwan Abdel Aal # general username
  avatar: /assets/img/avatar.jpg

# displayed in the footer
  github: sabdelaal
  twitter: 
  facebook: 
  patreon: 
  twitch: 
  youtube: 
  linkedin: safwanabdelaal

# URL settings
url: "https://safwan.com"
permalink: /:categories/:title
google_analytics:
umami:
  url: https://stats.tecios.de/script.js
  id: 1a5b0781-544a-4321-8a6a-dae4aa0614f1
fb_appid:


# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: true

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - klise-*.gem
  - klise.gemspec
  - default.nix

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap


#-------------------------

# Build settings
theme: minima
plugins:
  - jekyll-feed


# Collections
#permalink: /blog/:title

#collections:
  #ideas:
   # output: true
    #permalink: /ideas/:title/
    #layout: default




#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: sabdelaal
linkedin_username: safwanabdelaal
instagram_username: safwanjo
scholar_username:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
