name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Bundler
      run: |
        gem install bundler -v 2.4.22
        bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Updated to the latest version
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: sabdelaal/sabdelaal.github.io
        publish_dir: ./_site
